### ISSUE TITLE
Switch to a more usable list.txt format and support more functionality?

### ISSUE THREAD

**Issue by FabianBartl** [MakD/Jellyfin-Media-Bar#43]
I don't like the format used because:
 
- the name of the playlist has no purpose
- when you edit the list later, you don't know which movies the item IDs belong to unless you test them one by one
- no comments are supported

I suggest using a standard format like YAML as it supports the following features:

- Comments, so you can write the title after the element ID
- ordered lists
- objects to wrap the lists and assign more details
- multiple lists can be defined
- a separate entry could indicate which list is active instead of specifying a different file
- conditional selection of the playlist (would be an additional nice feature)

JSON would work to, especially as it is a JavaScript native format. But it does not support comments, which is important to mark the unreadable element IDs.

Detailed example: [example.yaml](https://github.com/FabianBartl/jellyfin-mediabar-listgen/blob/main/example.yaml)
```yaml
selection:
  - name: christmas movies
    days: 20-26
    months: 12
  - name: featured for kids
    user_age: -13
  - name: featured

playlists:
  - name: christmas movies
    sort_by: Name
    items:
      type: dynamic
      limit: 10
      include:
        tags: christmas
        genres: comedy, family
        library_ids: 7a2175bccb1f1a94152cbd2b2bae8f6d   # movies lib
      exclude:
        item_ids: acbc271cf5cdad562c98553a481bfd8c

  - name: featured for kids
    sort_by: order
    items:
      type: static
      ids:
        - c8d5976a20521b1ec16f9ee194a8af21    # spiderman
        - 2f0fe3e99b96b08ec40dfd221cf6f3e7    # big hero 6
  - name: featured
    sort_by: Name
    items:
      type: static
      ids:
        - 74b4484284a4dca6400b08edf3866053    # the godfather
        - d139b08fb71938d33a3eff45eb1cecc0    # matrix
        - 6cdca84774c614abc925476cf16215a6    # inception
```

The attribute names for filtering should probably be the same as those used by the Jellyfin API, although this not currently being the case in my example.

The format supports static and dynamic playlists. A list, their type, filters and sorting is defined in the `playlists` object. What list will be selected is evaluated with the `selection` object, which defines conditions for each playlist. The first entry that matches all conditions will be selected.

**Comment by FabianBartl** [comment]
I'm working on a Python script to generate a list of item IDs based on such a YAML configuration. This could be run via a cron job to update the list.txt file on the server every hour or so.

**Comment by olig89** [comment]
Adding to this as an option for deeper functionality.

I'd love to sue the banner to feature a different weekly film, so being able to pre-programme a bunch of films with from-to dates, and leave it to cycle through would be amazing.

**Comment by FabianBartl** [comment]
@olig89 this might be already supported by multiple static playlists and using the `weeks` condition in the selection. The `weeks` compares the current calender week to the set Interval. All supported date and time conditions are checked [here](https://github.com/FabianBartl/jellyfin-mediabar-listgen/blob/main/listgen.py#L672-L692) in the code.

```yaml
selection:
  - name: pl1
    weeks: 1
  - name: pl2
    weeks: 2-3

playlists:
  - name: pl1
    items:
      type: static
      ids: c8d5976a20521b1ec16f9ee194a8af21    # spiderman

  - name: pl2
    items:
      type: static
      ids:
        - e4927abf7601fdac27e70cbb7e4b8092    # paddington
        - 6fd2aba01ec88eb4c2949acd9a61582e    # the lego movie
```
